# Generated by Django 3.2.7 on 2023-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_mcid', models.CharField(max_length=16, null=True, unique=True)),
                ('priority_access', models.BooleanField(default=False, verbose_name='priorityAccess')),
                ('subscription_plan', models.CharField(max_length=16, null=True, verbose_name='SubscriptionPlan')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_mcid',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='MCID_main'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='priority_access',
            field=models.BooleanField(default=False, verbose_name='priorityAccess'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(max_length=16, null=True, verbose_name='SubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_mcids',
            field=models.ManyToManyField(related_name='MCIDs_sub', to='users.SubMCID'),
        ),
    ]
