# Generated by Django 3.2.7 on 2023-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231124_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False, verbose_name='Confirm')),
                ('price', models.IntegerField(default=0, verbose_name='DonationPrice')),
                ('detail', models.CharField(max_length=64, null=True, verbose_name='PaymentDetail')),
                ('purpose', models.CharField(choices=[('anything', '用途を限定しない'), ('server_cost', 'サーバー運用費')], max_length=16, null=True, verbose_name='Purpose')),
                ('type', models.CharField(choices=[('rank_apply', 'ランク申し込み'), ('rank_update', 'ランク更新'), ('rank_continue', 'ランク継続'), ('rank_cancel', 'ランク解約'), ('donation', '寄付')], max_length=16, verbose_name='Type')),
                ('donator_discount', models.BooleanField(default=False, verbose_name='DonatorDiscount')),
                ('plan_date', models.DateField(null=True, verbose_name='PlanStartDate')),
                ('month', models.IntegerField(default=0, verbose_name='Month')),
                ('apply_date', models.DateField(null=True, verbose_name='ApplyDate')),
                ('confirm_date', models.DateField(null=True, verbose_name='ConfirmDate')),
            ],
        ),
        migrations.CreateModel(
            name='MinecraftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_uuid', models.UUIDField(null=True, unique=True, verbose_name='UUID')),
                ('edition', models.CharField(choices=[('java', 'Java Edition'), ('bedrock', 'Bedrock Edition')], max_length=16, null=True, verbose_name='Edition')),
                ('total_donation', models.IntegerField(default=0, verbose_name='TotalDonation')),
                ('priority_access', models.BooleanField(default=False, verbose_name='PriorityAccess')),
                ('rank_plan', models.CharField(choices=[('gold', 'Gold'), ('jewelry', 'Jewelry')], max_length=16, null=True, verbose_name='RankPlan')),
                ('plan_start_date', models.DateField(null=True, verbose_name='PlanStartDate')),
                ('plan_end_date', models.DateField(null=True, verbose_name='PlanEndDate')),
                ('plan_change_date', models.DateField(null=True, verbose_name='PlanChangeDate')),
                ('change_plan', models.CharField(choices=[('gold', 'Gold'), ('jewelry', 'Jewelry')], max_length=16, null=True, verbose_name='ChangeRankPlan')),
                ('used_donator_discount', models.BooleanField(default=False, verbose_name='UsedDonatorDiscount')),
                ('application_logs', models.ManyToManyField(related_name='Application', to='users.Application')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='main_mcid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='priority_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_mcids',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_plan',
        ),
        migrations.DeleteModel(
            name='SubMCID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='minecraft_accounts',
            field=models.ManyToManyField(related_name='Minecraft_Accounts', to='users.MinecraftAccount'),
        ),
    ]
